version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.20.2
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9095:9095"
      - "9000:9000"
    links:
      - ext-authz
      - backend
  ext-authz:
    build:
      context: ./ext-authz
      dockerfile: Dockerfile 
    ports:
      - "50051:50051"
      - "8080:8080"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "8002:8002"
